namespace: mernapp
ingress:
  name: mern-ing
  namespace: mernapp
  ingressClassName: nginx-mern          # IMPORTANT: matches the second controller
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: app-mldevops-org-tls
  host: app.mldevops.org
  rules:
    - path: /
      service: { name: frontend-service, port: 80 }
    - path: /api
      service: { name: backend-service,  port: 5000 }