apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mern-backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mern-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mern-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.container.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.container.secret.name }}
          readinessProbe:
            httpGet: { path: /health, port: {{ .Values.container.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: {{ .Values.container.port }} }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
{{- toYaml .Values.resources | nindent 12 }}