name: mern-frontend
namespace: mernapp
replicas: 1
container:
  image: "REPLACED_BY_JENKINS"
  port: 80
  env: []
service:
  type: ClusterIP
  port: 80
resources:
  requests: { cpu: 50m,  memory: 64Mi }
  limits:   { cpu: 300m, memory: 256Mi }