apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mern-frontend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mern-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mern-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.container.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
{{- toYaml .Values.container.env | nindent 12 }}
          readinessProbe:
            httpGet: { path: /, port: {{ .Values.container.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: {{ .Values.container.port }} }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
{{- toYaml .Values.resources | nindent 12 }}