name: mern-backend
namespace: mernapp
replicas: 1
container:
  image: "REPLACED_BY_JENKINS"   # Jenkins overrides to ECR URI:TAG
  port: 5000
  secret:
    name: mongodb-cred
service:
  type: ClusterIP
  port: 5000
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }